### ISSUE TITLE
2.7. Završetak vožnje

### ISSUE THREAD

**Issue by tanitamosic** [tanitamosic/NWT-KTS-project#18]
Nakon što je vožnja obavljena i putnici su izašli iz vozila, vozač označava da je vožnja gotova i time prelazi u dostupno stanje ako nema drugu zakazanu vožnju. U slučaju postojanja zakazane, učitavaju mu se novi podaci i kreće ka novom polazištu. Putnici mogu ponovo poručivati nove vožnje.

- [x] označavanje i promena stanja vozača
- [x] učitavanje novih podataka
- [x] dopuštanje naručivanja putnicima

**Comment by Cabbagito** [comment]
Odradjen Backend.
Vozac moze da oznaci da je voznja gotova i u zavisnosti da li ima PENDING voznji, to mu se posalje kao odgovor. I ukoliko ima jednu ili nula PENDING voznji, vozac postaje dostupan za nove voznje.

**Comment by Cabbagito** [comment]
Vozac moze da oznaci da je voznja gotova i u zavisnosti da li ima PENDING voznji, to mu se posalje kao odgovor. I ukoliko ima jednu ili nula PENDING voznji, vozac postaje dostupan za nove voznje.
