### ISSUE TITLE
2.8. Ocenjivanje vozila i vozača

### ISSUE THREAD

**Issue by tanitamosic** [tanitamosic/NWT-KTS-project#19]
Nakon završetka, svim putnicima (onom koji je poručio vožnju i svim ulinkovanim korisnicima) nudi se opcija da ocene vozilo, vozača i ostave komentar. To mogu uraditi odmah nakon vožnje ili odlaskom na pregled istorije vožnji odakle mogu naknadno da ostave ocenu. Rok za ostavljanje ocene je 3 dana od završetka vožnje. Ako rok istekne, ista se smatra neocenjenom.

**Comment by Cabbagito** [comment]
Odradjeno slanje Ocena bez checkova za datum. Ovo ce se uraditi kada se bude radilo testiranje.
